### PR TITLE
Deployment scripts for EC gateway and load balancer

### LINKED ISSUE #6: Gateway load balancing - Terraform scripts for auto deployment
Create terraform scripts for - 

- Provisioning the 2 VM's for deploying gateway load balancer and watcher
- Deploy load balancer in a VM
- Deploy watcher in other VM

### PR DESCRIPTION
**Pull request by ramaraosrikakulapu**
Terraform automation deployment scripts for - 

- Deploying EC gateway in VM's
- Deploying EC gateway load balancer 
- Targeted env - AWS
- Documentation

### CODE REVIEW

**Comment by ayasuda2OO3** [comment]
I am inclined to merge, however, I also like to see if there exist a test mechanism to validate the script? @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
Thanks @ayasuda2003 .. I do not have test mechanism, but here are the attached logs while executing the scripts. Hope this helps !!
[output.txt](https://github.com/Enterprise-connect/oci/files/4783087/output.txt)

**Comment by ayasuda2OO3** [comment]
> Thanks @ayasuda2003 .. I do not have test mechanism, but here are the attached logs while executing the scripts. Hope this helps !!
> [output.txt](https://github.com/Enterprise-connect/oci/files/4783087/output.txt)

Can you check this? https://www.terraform.io/docs/github-actions/index.html. We need to be able to provide a mvp as a working example for adoption.

**Comment by ramaraosrikakulapu** [comment]
> > Thanks @ayasuda2003 .. I do not have test mechanism, but here are the attached logs while executing the scripts. Hope this helps !!
> > [output.txt](https://github.com/Enterprise-connect/oci/files/4783087/output.txt)
> 
> Can you check this? https://www.terraform.io/docs/github-actions/index.html. We need to be able to provide a mvp as a working example for adoption.

Will take a look.. Thanks @ayasuda2003

**Comment by ramaraosrikakulapu** [comment]
@ayasuda2003 .. I implemented github actions as suggested. I am able to add steps for 
 initiating the process and able to do some basic checks like format. But in order to ```plan``` or ```apply``` workflow is expecting a tfvars file and it should have env configuration details like subnets, security groups. So please advise, if I can checkin tfvars file.

[Here](https://github.com/Enterprise-connect/oci/actions) is the link for workflow status

**Comment by ramaraosrikakulapu** [comment]
@ayasuda2003 as discussed, I am now checking for unit test cases for deployment scripts in ```go lang```

**Comment by ramaraosrikakulapu** [comment]
Update - 

- Tested and checked in integration test case. Logs are attached.
- WIP for CI with github actions terraform workflow. Stuck with an issue for passing the values to variables. Have to do some research on it.

[integration-test-logs.txt](https://github.com/Enterprise-connect/oci/files/4819514/integration-test-logs.txt)

**Review by ayasuda2OO3 — COMMENTED** [review]
Let' discussion the reversal of these commits and strategy for the script deployment test. @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
@ayasda2003 .. can you please share your input on the PR. I am planning to put github actions CI as separate one for future changes as I have to do some more changes and research on it.

**Review by ayasuda2OO3 — APPROVED** [review]

**Pull request merged**
