### PR TITLE
Notes.txt file removal from template folder in Helm

### LINKED ISSUE #7: Not able to add AGENT package to my deployment
Im getting below error while adding this to my helm repo:

Error: looks like "https://enterprise-connect.github.io/oci/k8s/pkg/agent/" is not a valid chart repository or cannot be reached: failed to fetch https://enterprise-connect.github.io/oci/k8s/pkg/agent/index.yaml : 404 Not Found

### PR DESCRIPTION
**Pull request by simran3695**
### Purpose
We are trying to install EC agent application on our TC EKS Cluster. While deploying we are getting error on the ingress object in the Notes.txt file in the agent+helper template folder. As we can render Notes.txt we need to remove the file completely and test it out.

### Proposal
Remove the Notes.txt file in the helm chart.

### Expected Behaviour
1) The agent chart pkg can be deployed successfully by Argo.
2) Any subsidiary pkgs associated with the agent can be deployed successfully by Argo.

### CODE REVIEW

**Review by ayasuda2OO3 — CHANGES_REQUESTED** [review]
Can you paste this note to the PR content as will? @simran3695 we will propose the removal of the txt files.

**Comment by ayasuda2OO3** [comment]
> Added the comments in changes.txt file in agent+helper repo.

And what is the Goal(s) of this PR? Propose an outcome/solution? @simran3695

**Comment by simran3695** [comment]
while installing agent+helper helm we are getting errors on Notes.txt file complaining on the ingress object. As notes.txt can be rene=dered we would like to delete notes.txt from helm template and test it. Also we saw agent+helper cannot be deployed alone as it is just a library we will now be deploying agent helm along with the agent+helper as the dependency object.

**Comment by ayasuda2OO3** [comment]
> while installing agent+helper helm we are getting errors on Notes.txt file complaining on the ingress object. As notes.txt can be rene=dered we would like to delete notes.txt from helm template and test it. Also we saw agent+helper cannot be deployed alone as it is just a library we will now be deploying agent helm along with the agent+helper as the dependency object.

@simran3695 please put and modify it [here](https://github.com/Enterprise-connect/oci/pull/12#issue-426693934)

**Comment by simran3695** [comment]
- Purpose -> We are trying to install EC agent application on our TC EKS Cluster. While deploying we are getting error on the ingress object in the Notes.txt file in the agent+helper template folder. As we can render Notes.txt we need to remove the file completely and test it out.

- Proposal -> Remove the Notes.txt file in the helm chart.

**Comment by ayasuda2OO3** [comment]
please verify. @simran3695

**Comment by ayasuda2003** [comment]
#7

**Review by ayasuda2OO3 — APPROVED** [review]
approved based on [the feedback](https://github.com/Enterprise-connect/oci/issues/7#issuecomment-635839680) #7

**Pull request merged**
